#!/bin/bash

git clone git@github.com:Shougo/neobundle.vim.git ~/.vim/bundle/neobundle.vim

git -C ~/.vim/bundle/neobundle.vim checkout e4e6766

echo
echo 'NeoBundle successfully installed. Open vim to install bundles.'
echo
